### ISSUE TITLE
customizable time zone and colors

### ISSUE THREAD

**Issue by spitzlbergerj** [mykle1/MMM-EventHorizon#3]
Hi, 

I live in Germany, so I had to adjust the time zone. I also wanted to adjust the colors of the fonts and the background.

So I added these parameters to the module. 

Here is the changed MMM-EventHorizon.js 
[MMM-EventHorizon.zip](https://github.com/mykle1/MMM-EventHorizon/files/2752982/MMM-EventHorizon.zip)

The addition for the readme could be taken directly from the js file.

Would you like to use it as a new version? Then I would not have to follow the changes with updates of you ;-)

Thanks
Josef

**Comment by mykle1** [comment]
Hi Josef, (my middle name = Joseph)

Yes, I would like to add this functionality to the module but what about the other time zones? I would need a code list of the 24 major timezones. Your request only uses Germany, Berlin. I'm in NYC. You left me out! haha

If you can contact me at the MagicMirror forum that would be great. I don't often look in here.

EDIT!

Ok, don't do anything. There are just too many cities to deal with. I have a workaround for the timezones which includes users contributing their timezone codes to the module OR the url to the page so they can acquire a city code.

FYI, the url WILL accept full 6-digit hex color codes. I'm going with that because I don't want to confuse anyone with the shorthand color codes. I very happy with your contribution. Thank you my friend.!
